#### Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files. Delete the found duplicate file.
[Hint: use hashlib]

In [2]:
import os
from pathlib import Path
from filecmp import cmp
  
  
# list of all documents
DATA_DIR = Path('C:/Users/skarmakar/Assess')
files = sorted(os.listdir(DATA_DIR))

duplicateFiles = []
  
for file_x in files:
  
    if_dupl = False
  
    for class_ in duplicateFiles:
        if_dupl = cmp(
            DATA_DIR / file_x,
            DATA_DIR / class_[0],
            shallow=False
        )
        if if_dupl:
            class_.append(file_x)
            break
  
    if not if_dupl:
        duplicateFiles.append([file_x])
  
print(duplicateFiles)

[['Hello.txt', 'World.txt', 'duplicate.txt'], ['Test.txt'], ['abc.txt.txt', 'pqr.txt'], ['xyz.txt.txt']]


In [4]:
for i in duplicateFiles:
    if len(i)>1:
        del i[1:]
print(duplicateFiles)

[['Hello.txt'], ['Test.txt'], ['abc.txt.txt'], ['xyz.txt.txt']]


#### 2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters. Using these packages [random, strings]

In [7]:
import random
import string
for _ in range(2):
    lower = string.ascii_lowercase
for _ in range(2):
    digits = string.digits
for _ in range(1):
    upper = string.ascii_uppercase
special = string.punctuation
password = lower + upper + digits + special
temporary = random.sample(password,6)
pswd  = "".join(temporary)
print(pswd)

R9vWNe


#### 3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [6]:
import math
import numpy as np
def prime(n):
    c = 0
    i = 1
    for i in range(n):
        if n%i == 0:
            c += 1;
    if c == 2:
        return True
    else:
        return False

arr = np.arange(0,16).reshape(4,4)
for i in range(17):
    for j in range(17):
        n = i * 17 + j + 1
        if prime(n):
            arr[i][j] = n**3;
            
for i in range(17):
    for j in range(17):
        print(arr[i][j], end=" ")
    print()

ZeroDivisionError: integer division or modulo by zero

#### 6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [9]:
import numpy as np
arr = np.zeros((7,7))
for i in range(7):
    for j in range(7):
        arr[i][j] = (i+1) * (j+1) * 7
              
print("Last element of the array is: ", (arr[6][6]))

[[  7.  14.  21.  28.  35.  42.  49.]
 [ 14.  28.  42.  56.  70.  84.  98.]
 [ 21.  42.  63.  84. 105. 126. 147.]
 [ 28.  56.  84. 112. 140. 168. 196.]
 [ 35.  70. 105. 140. 175. 210. 245.]
 [ 42.  84. 126. 168. 210. 252. 294.]
 [ 49.  98. 147. 196. 245. 294. 343.]]
Last element of the array is:  343.0


#### 7.	Checker Board Pattern

In [1]:
import numpy as np
x = np.ones((5,5))
x[1::2,0::2] = 0
x[0::2,1::2] = 0
x

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

#### 8.	Create a given Matrix:
####   [  A, B, C, D
####      E, F, G, H
####      I, J, K, L
####      M, N, O, P
####      Q, R, S, T
####      U, V, W, X ]

#### Replace all the vowels by np.nan
#### A, E, I, O U  -- >  np.nan
#### Return the count of the missing values

In [5]:
import numpy as np
x = np.array([['A','B','C','D'],['E','F','G','H'],['I','J','K','L'],['M','N','O','P'],['Q','R','S','T'],['U','V','W','X']])
list_1 = list(x)
for i in range(len(list_1)):
    for j in range(len(list_1[i])):
        if list_1[i][j]=='A' or list_1[i][j]=='E' or list_1[i][j]=='I' or list_1[i][j]=='O' or list_1[i][j]=='U':
            list_1[i][j] = np.nan
print(list_1)

[array(['n', 'B', 'C', 'D'], dtype='<U1'), array(['n', 'F', 'G', 'H'], dtype='<U1'), array(['n', 'J', 'K', 'L'], dtype='<U1'), array(['M', 'N', 'n', 'P'], dtype='<U1'), array(['Q', 'R', 'S', 'T'], dtype='<U1'), array(['n', 'V', 'W', 'X'], dtype='<U1')]
