#### 1. Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files. Delete the found duplicate file.
[Hint: use hashlib]

In [1]:
import os
from pathlib import Path
from filecmp import cmp
  
  
# list of all documents
DATA_DIR = Path('C:/Users/skarmakar/Assess')
files = sorted(os.listdir(DATA_DIR))

duplicateFiles = []
  
for file_x in files:
  
    if_dupl = False
  
    for class_ in duplicateFiles:
        if_dupl = cmp(
            DATA_DIR / file_x,
            DATA_DIR / class_[0],
            shallow=False
        )
        if if_dupl:
            class_.append(file_x)
            break
  
    if not if_dupl:
        duplicateFiles.append([file_x])
  
print(duplicateFiles)

[['Hello.txt', 'World.txt', 'duplicate.txt'], ['Test.txt'], ['abc.txt.txt', 'pqr.txt'], ['xyz.txt.txt']]


In [2]:
for i in duplicateFiles:
    if len(i)>1:
        del i[1:]
print(duplicateFiles)

[['Hello.txt'], ['Test.txt'], ['abc.txt.txt'], ['xyz.txt.txt']]


#### 2.	Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters. Using these packages [random, strings]

In [3]:
import random
import string
for _ in range(2):
    lower = string.ascii_lowercase
for _ in range(2):
    digits = string.digits
for _ in range(1):
    upper = string.ascii_uppercase
special = string.punctuation
password = lower + upper + digits + special
temporary = random.sample(password,6)
pswd  = "".join(temporary)
print(pswd)

|-lm}?


#### 3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [15]:
import numpy as np
rows = int(input("Enter the number of rows:"))
columns = int(input("Enter the number of columns: "))
arr = np.empty((rows,columns))
for i in range(rows):
    for j in range(columns):
        arr[i][j] = int(input("Enter the elements of array: "))
        
        
def prime(num):
    c = 0
    i = 1
    while i<=num:
        if num%i==0:
            c += 1
        i += 1
    if c == 2:
        return True
    else:
        return False

count = 1
for i in range(rows):
    for j in range(columns):
        if prime(count):
            arr[i][j] = arr[i][j]**3
        count += 1

print(arr)

Enter the number of rows:3
Enter the number of columns: 3
Enter the elements of array: 1
Enter the elements of array: 2
Enter the elements of array: 3
Enter the elements of array: 4
Enter the elements of array: 5
Enter the elements of array: 6
Enter the elements of array: 7
Enter the elements of array: 8
Enter the elements of array: 9
[[  1.   8.  27.]
 [  4. 125.   6.]
 [343.   8.   9.]]


#### 4. Python program to get the sum of every cubed value and its previous integer.

In [18]:
import numpy as np
rows = int(input("Enter the number of rows:"))
columns = int(input("Enter the number of columns: "))
arr = np.empty((rows,columns))
for i in range(rows):
    for j in range(columns):
        arr[i][j] = int(input("Enter the elements of array: "))
        
        
def prime(num):
    c = 0
    i = 1
    while i<=num:
        if num%i==0:
            c += 1
        i += 1
    if c == 2:
        return True
    else:
        return False

count = 1
for i in range(rows):
    for j in range(columns):
        if prime(count):
            arr[i][j] = arr[i][j]**3 + arr[i][j-1]
        count += 1

print(arr)

Enter the number of rows:3
Enter the number of columns: 3
Enter the elements of array: 1
Enter the elements of array: 2
Enter the elements of array: 3
Enter the elements of array: 4
Enter the elements of array: 5
Enter the elements of array: 6
Enter the elements of array: 7
Enter the elements of array: 8
Enter the elements of array: 9
[[  1.   9.  36.]
 [  4. 129.   6.]
 [352.   8.   9.]]


##### 5.	Given two arrays, find their intersection. Examples:

#### Input:  arr1[] = [1, 3, 4, 5, 7]
####             arr2[] = [2, 3, 5, 6]

In [5]:
import numpy as np

arr1 = np.array([1,3,4,5,7])
arr2 = np.array([2,3,5,6])

def intersection(arr1,arr2):
    return np.intersect1d(arr1,arr2)

print(intersection(arr1,arr2))

[3 5]


#### 6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [6]:
import numpy as np
arr = np.zeros((7,7))
for i in range(7):
    for j in range(7):
        arr[i][j] = (i+1) * (j+1) * 7
              
print("Last element of the array is: ", (arr[6][6]))

Last element of the array is:  343.0


#### 7.	Checker Board Pattern

In [7]:
import numpy as np
x = np.ones((5,5))
x[1::2,0::2] = 0
x[0::2,1::2] = 0
x

array([[1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.],
       [0., 1., 0., 1., 0.],
       [1., 0., 1., 0., 1.]])

#### 8.	Create a given Matrix:
####   [  A, B, C, D
####      E, F, G, H
####      I, J, K, L
####      M, N, O, P
####      Q, R, S, T
####      U, V, W, X ]

#### Replace all the vowels by np.nan
#### A, E, I, O U  -- >  np.nan
#### Return the count of the missing values

In [8]:
import numpy as np
x = np.array([['A','B','C','D'],['E','F','G','H'],['I','J','K','L'],['M','N','O','P'],['Q','R','S','T'],['U','V','W','X']])
list_1 = list(x)
for i in range(len(list_1)):
    for j in range(len(list_1[i])):
        if list_1[i][j]=='A' or list_1[i][j]=='E' or list_1[i][j]=='I' or list_1[i][j]=='O' or list_1[i][j]=='U':
            list_1[i][j] = np.nan
print(list_1)

[array(['n', 'B', 'C', 'D'], dtype='<U1'), array(['n', 'F', 'G', 'H'], dtype='<U1'), array(['n', 'J', 'K', 'L'], dtype='<U1'), array(['M', 'N', 'n', 'P'], dtype='<U1'), array(['Q', 'R', 'S', 'T'], dtype='<U1'), array(['n', 'V', 'W', 'X'], dtype='<U1')]
